"""Сбор ИИ-кода: репозитории, созданные после выхода ChatGPT и явно помеченные
в README/описании как сгенерированные LLM.

Метки шумные => после сбора обязательна ручная проверка (verify_sample.py).

Запуск:  python -m src.collect.collect_ai --max-files 300
"""
import argparse
import re
import random

from src.collect.common import (
    content_hash,
    is_relevant_path,
    is_valid_python,
    load_seen_hashes,
    save_file,
)
from src.collect.github_client import GitHubClient
from src.config import GITHUB_API, MAX_FILES_PER_REPO, RAW_AI_DIR, RAW_HUMAN_DIR

# Поисковые запросы по README/описанию. created:>2022-11-01 => после ChatGPT.
QUERIES = [
    '"generated by ChatGPT" language:Python created:>2022-11-01 stars:10..200000',
    '"AI-generated" language:Python created:>2022-11-01 stars:10..200000',
]

# Подтверждающие маркеры в README — снижают шум меток.
_README_MARKERS = re.compile(
    r"(generated by chatgpt|written by chatgpt|generated by gpt|ai[- ]generated"
    r"|github copilot|fully generated by|created by chatgpt)",
    re.IGNORECASE,
)


def _readme_confirms_ai(client: GitHubClient, full_name: str) -> bool:
    """Скачивает README и проверяет наличие AI-маркера."""
    try:
        resp = client._get(f"{GITHUB_API}/repos/{full_name}/readme")
    except Exception:  # noqa: BLE001 - README может отсутствовать
        return False
    import base64

    data = resp.json()
    if data.get("encoding") != "base64":
        return False
    try:
        text = base64.b64decode(data["content"]).decode("utf-8", errors="ignore")
    except (ValueError, UnicodeDecodeError):
        return False
    return _README_MARKERS.search(text) is not None


def collect(max_files: int) -> None:
    client = GitHubClient()
    seen = load_seen_hashes(RAW_HUMAN_DIR, RAW_AI_DIR)
    saved = 0

    for query in QUERIES:
        if saved >= max_files:
            break
        print(f"\n=== Запрос: {query} ===")
        for repo in client.search_repositories(query, max_repos=1000, sort="updated"):
            if saved >= max_files:
                break
            full_name = repo["full_name"]
            if not _readme_confirms_ai(client, full_name):
                continue
            branch = repo.get("default_branch", "main")
            try:
                files = client.list_python_files(full_name, branch)
            except Exception as exc:  # noqa: BLE001
                print(f"  ! {full_name}: {exc}")
                continue

            taken_here = 0
            for node in files:
                if saved >= max_files or taken_here >= MAX_FILES_PER_REPO:
                    break
                if not is_relevant_path(node["path"]):
                    continue
                source = client.get_blob_content(full_name, node["sha"])
                if not source or not is_valid_python(source):
                    continue
                h = content_hash(source)
                if h in seen:
                    continue
                seen.add(h)
                save_file(
                    source,
                    RAW_AI_DIR,
                    label="ai",
                    repo=full_name,
                    url=repo["html_url"],
                    source_signal=query,
                )
                saved += 1
                taken_here += 1
            if taken_here:
                print(f"  + {full_name}: {taken_here} файл(ов) (всего {saved})")

    print(f"\nГотово. Сохранено ИИ-файлов: {saved}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-files", type=int, default=300)
    args = parser.parse_args()
    collect(args.max_files)
